language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm test

# sudo: false

# after_success:
#   - npm run report-coveralls
#   - npm run report-codecov

notifications:
  webhooks:
    urls:
      # dbwebb-se/ramverk2
      - https://webhooks.gitter.im/e/04132ac4ce5f7823f96c
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
